changelog:
  categories:
    - title: '🥳 Breaking Changes'
      labels:
        - BREAKING CHANGE
    - title: '🔥 New Features and Enhancements'
      labels:
        - enhancement
    - title: '🐛 Fixes'
      labels:
        - bug
    - title: '📖 Changes to Documentation'
      labels:
        - "documentation"
    - title: '🛠️ Changes in Dependencies'
      labels:
        - "dependencies"
    - title: '📎 Other Changes'
      labels:
        - "*"