---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Media:
    - Plex:
        icon: plex.png
        href: "http://plex.server.local"
        description: "Plex Media Server"
        server: my-docker
        container: plex
