title: server.local
startUrl: http://server.local/
background:
  image: /images/background.jpg
  opacity: 40
cardBlur: sm
favicon: /images/favicon-32x32.png
theme: dark
color: slate
headerStyle: clean
base: http://server.local/
language: es
target: _self
hideVersion: true
showStats: true
statusStyle: "dot"
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: bing
providers:
  - weatherapi:
      latitude: 50.449684
      longitude: 30.525026
      provider: weatherapi
layout:
  Bookmark Group on First Tab:
    tab: First

  First Service Group:
    tab: First
    style: row
    columns: 4

  Second Service Group:
    tab: Second
    columns: 4

  Third Service Group:
    tab: Third
    style: row

  Bookmark Group on Fourth Tab:
    tab: Fourth

  Service Group on every Tab:
    style: row
    columns: 4
